# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 09:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20151201_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='area',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Paste any custom <a href="http://geojson.io">GeoJSON</a> here', null=True),
        ),
    ]
