# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_remove_annotation_link_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['title'], 'verbose_name_plural': 'media'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 28, 15, 12, 19, 923668, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
