# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_auto_20151228_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='annotations', to='maps.Media'),
        ),
    ]
