# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 14:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_annotation_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='alt_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, help_text='Multiple alternative names allowed, press Enter between entires', null=True, size=None),
        ),
    ]
