# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_auto_20160221_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='media_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_as_icon', to='maps.Media'),
        ),
    ]
