# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 09:27
from __future__ import unicode_literals

from django.db import migrations, models


def reorg_annotations(apps, schema_editor):
    diff = {
        'correspondence': 'communication',
        'travel': 'path',
        'origin': 'reference',
        'quote': 'reference',  # none of these actually exist
        'trend': 'reference'  # neither do these
    }
    Annotation = apps.get_model('maps', 'Annotation')
    for k, v in diff.items():
        Annotation.objects.filter(type=k).update(type=v)


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_event_media_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='type',
            field=models.CharField(choices=[('group', 'Group'), ('reference', 'Reference'), ('communication', 'Communication'), ('path', 'Path')], max_length=20),
        ),
        migrations.RunPython(reorg_annotations),
    ]
