# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_auto_20160606_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='zoomlevel',
            field=models.CharField(choices=[('area', 'Area'), ('metropolis', 'Metropolis'), ('largecity', 'Large City'), ('city', 'City'), ('town', 'Town'), ('site', 'Site')], default='city', max_length=20, verbose_name='Zoom level'),
        ),
    ]
