# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_auto_20160606_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='circa_date',
            field=models.BooleanField(default=False),
        ),
    ]
