# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 08:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0020_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, help_text='Multiple tags allowed, press Enter between entries', null=True, size=None),
        ),
    ]
