# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-06 11:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_auto_20160713_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]