# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-20 14:21
from __future__ import unicode_literals

import ckeditor.fields
import daat.maps.models
import daat.maps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_auto_20160713_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attribution_line',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Group description'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='title',
            field=models.CharField(blank=True, help_text='Group title', max_length=160),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=daat.maps.models.PartialDateCharField(blank=True, help_text='Date in YYYY-MM-DD format, use 00 to denote month/day ranges', max_length=10, validators=[daat.maps.utils.partial_date_validator]),
        ),
    ]
