# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-06 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0022_media_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='description',
            new_name='remarks',
        ),
    ]