# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-20 16:28
from __future__ import unicode_literals

import ckeditor.fields
import daat.maps.models
import daat.maps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0023_auto_20170206_1125'),
    ]

    operations = []
