# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-20 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0022_auto_20170320_1421'),
        ('maps', '0023_auto_20170206_1125'),
    ]

    operations = [
    ]
