# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0024_auto_20170320_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='edit_mode',
            field=models.CharField(blank=True, choices=[('Edited', 'Edited'), ('NotEdited', 'Not Edited'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
