# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0025_event_edit_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='edit_mode',
            field=models.CharField(blank=True, choices=[('Edited', 'Edited'), ('NotEdited', 'Not Edited'), ('Pending', 'Pending')], default='NotEdited', max_length=20),
        ),
    ]
