# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-04 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_auto_20170404_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='edit_mode',
            field=models.CharField(choices=[('Edited', 'Edited'), ('NotEdited', 'Not Edited'), ('Pending', 'Pending')], default='NotEdited', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='edit_mode',
            field=models.CharField(choices=[('Edited', 'Edited'), ('NotEdited', 'Not Edited'), ('Pending', 'Pending')], default='NotEdited', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='edit_mode',
            field=models.CharField(choices=[('Edited', 'Edited'), ('NotEdited', 'Not Edited'), ('Pending', 'Pending')], default='NotEdited', max_length=20),
        ),
    ]
