# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-07 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0028_auto_20170404_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='viaf_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='person',
            name='viaf_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='place',
            name='viaf_id',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
