# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-08 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0029_auto_20170607_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('project', models.CharField(blank=True, max_length=160, verbose_name='Temp Project Name')),
                ('csv', s3direct.fields.S3DirectField(blank=True)),
                ('media', s3direct.fields.S3DirectField(blank=True)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='maps.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
