# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0031_auto_20170608_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='error_log',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('uploading', 'uploading'), ('uploaded', 'uploaded'), ('testing', 'Testing')], default='new', max_length=20),
        ),
    ]
