# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0032_auto_20170608_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='copyrights',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='import',
            name='copyrights_source_url',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='import',
            name='description1_subtitle',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='import',
            name='description2_subtitle',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='import',
            name='description3_subtitle',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
