# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-11 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0033_auto_20170611_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='csv',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='import',
            name='media',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='import',
            name='project',
            field=models.CharField(max_length=160, verbose_name='Temp Project Name'),
        ),
        migrations.AlterField(
            model_name='import',
            name='target_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='maps.Project'),
        ),
    ]
