# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-22 13:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0034_auto_20170611_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='map_context',
            field=models.CharField(blank=True, choices=[('neighbourhood', 'Neighbourhood'), ('city', 'City'), ('province', 'Province'), ('country', 'Country'), ('continent', 'Continent'), ('world', 'World')], max_length=20),
        ),
        migrations.AlterField(
            model_name='import',
            name='copyrights_source_url',
            field=models.CharField(blank=True, max_length=160, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('testing', 'Testing'), ('invalid', 'Invalid'), ('valid', 'Valid'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('migrating', 'Migrating'), ('migrated', 'Migrated'), ('failed', 'Failed'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='new', max_length=20),
        ),
    ]
