# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-05 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0038_event_data_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data_sets',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='maps.DataSet'),
        ),
    ]
